# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcPy_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import math


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 800)
        MainWindow.setMinimumSize(QtCore.QSize(520, 800))
        MainWindow.setMaximumSize(QtCore.QSize(520, 800))
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        MainWindow.setStyleSheet("background-color:#F2F2F2;\n"
"\n"
"btnOne {\n"
"background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(520, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(520, 800))
        self.centralwidget.setStyleSheet("background-color:#F2F2F2;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 0, 521, 801))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 10, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.displayContainer = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.displayContainer.setMinimumSize(QtCore.QSize(480, 250))
        self.displayContainer.setMaximumSize(QtCore.QSize(480, 250))
        self.displayContainer.setStyleSheet("background-color: #4B64F2;\n"
"border-radius: 50px;\n"
"")
        self.displayContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayContainer.setObjectName("displayContainer")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.displayContainer)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 481, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(50, 10, 50, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblExpression = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblExpression.setStyleSheet("font-family: sans-serif, \"Roboto\";\n"
"font-weight: 500;\n"
"color: #F2F2F2;\n"
"font-size: 20px;")
        self.lblExpression.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblExpression.setObjectName("lblExpression")
        self.verticalLayout_2.addWidget(self.lblExpression)
        self.lblResult = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblResult.setStyleSheet("font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"color: #F2F2F2;\n"
"font-size: 70px;")
        self.lblResult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout_2.addWidget(self.lblResult)
        self.verticalLayout.addWidget(self.displayContainer)
        self.btnsContainer = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.btnsContainer.setMinimumSize(QtCore.QSize(480, 500))
        self.btnsContainer.setMaximumSize(QtCore.QSize(480, 500))
        self.btnsContainer.setStyleSheet("background-color: #4B64F2;\n"
"border-radius: 50px;\n"
"")
        self.btnsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnsContainer.setObjectName("btnsContainer")
        self.gridLayoutWidget = QtWidgets.QWidget(self.btnsContainer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(25, 25, 25, 25)
        self.gridLayout.setObjectName("gridLayout")
        self.btnClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnClear.setMinimumSize(QtCore.QSize(80, 80))
        self.btnClear.setMaximumSize(QtCore.QSize(80, 80))
        self.btnClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClear.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnClear.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 0, 0, 1, 1)
        self.btnDivision = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDivision.setMinimumSize(QtCore.QSize(80, 80))
        self.btnDivision.setMaximumSize(QtCore.QSize(80, 80))
        self.btnDivision.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDivision.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDivision.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnDivision.setObjectName("btnDivision")
        self.gridLayout.addWidget(self.btnDivision, 0, 3, 1, 1)
        self.btnP1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnP1.setMinimumSize(QtCore.QSize(80, 80))
        self.btnP1.setMaximumSize(QtCore.QSize(80, 80))
        self.btnP1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnP1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnP1.setText("(")
        self.btnP1.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnP1.setObjectName("btnP1")
        self.gridLayout.addWidget(self.btnP1, 0, 1, 1, 1)
        self.btnP2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnP2.setMinimumSize(QtCore.QSize(80, 80))
        self.btnP2.setMaximumSize(QtCore.QSize(80, 80))
        self.btnP2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnP2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnP2.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnP2.setObjectName("btnP2")
        self.gridLayout.addWidget(self.btnP2, 0, 2, 1, 1)
        self.btnSeven = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSeven.setMinimumSize(QtCore.QSize(80, 80))
        self.btnSeven.setMaximumSize(QtCore.QSize(80, 80))
        self.btnSeven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSeven.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSeven.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnSeven.setObjectName("btnSeven")
        self.gridLayout.addWidget(self.btnSeven, 1, 0, 1, 1)
        self.btnFour = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFour.setMinimumSize(QtCore.QSize(80, 80))
        self.btnFour.setMaximumSize(QtCore.QSize(80, 80))
        self.btnFour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFour.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnFour.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnFour.setObjectName("btnFour")
        self.gridLayout.addWidget(self.btnFour, 2, 0, 1, 1)
        self.btnOne = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnOne.setMinimumSize(QtCore.QSize(80, 80))
        self.btnOne.setMaximumSize(QtCore.QSize(80, 80))
        self.btnOne.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOne.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnOne.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnOne.setObjectName("btnOne")
        self.gridLayout.addWidget(self.btnOne, 3, 0, 1, 1)
        self.btnElevate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnElevate.setMinimumSize(QtCore.QSize(80, 80))
        self.btnElevate.setMaximumSize(QtCore.QSize(80, 80))
        self.btnElevate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnElevate.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnElevate.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnElevate.setObjectName("btnElevate")
        self.gridLayout.addWidget(self.btnElevate, 4, 0, 1, 1)
        self.btnZero = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnZero.setMinimumSize(QtCore.QSize(80, 80))
        self.btnZero.setMaximumSize(QtCore.QSize(80, 80))
        self.btnZero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnZero.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnZero.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnZero.setObjectName("btnZero")
        self.gridLayout.addWidget(self.btnZero, 4, 1, 1, 1)
        self.btnDot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDot.setMinimumSize(QtCore.QSize(80, 80))
        self.btnDot.setMaximumSize(QtCore.QSize(80, 80))
        self.btnDot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDot.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnDot.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnDot.setObjectName("btnDot")
        self.gridLayout.addWidget(self.btnDot, 4, 2, 1, 1)
        self.btnEquals = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnEquals.setMinimumSize(QtCore.QSize(80, 80))
        self.btnEquals.setMaximumSize(QtCore.QSize(80, 80))
        self.btnEquals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEquals.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEquals.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnEquals.setObjectName("btnEquals")
        self.gridLayout.addWidget(self.btnEquals, 4, 3, 1, 1)
        self.btnTwo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnTwo.setMinimumSize(QtCore.QSize(80, 80))
        self.btnTwo.setMaximumSize(QtCore.QSize(80, 80))
        self.btnTwo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTwo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnTwo.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnTwo.setObjectName("btnTwo")
        self.gridLayout.addWidget(self.btnTwo, 3, 1, 1, 1)
        self.btnThree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnThree.setMinimumSize(QtCore.QSize(80, 80))
        self.btnThree.setMaximumSize(QtCore.QSize(80, 80))
        self.btnThree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnThree.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnThree.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnThree.setObjectName("btnThree")
        self.gridLayout.addWidget(self.btnThree, 3, 2, 1, 1)
        self.btnMinus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnMinus.setMinimumSize(QtCore.QSize(80, 80))
        self.btnMinus.setMaximumSize(QtCore.QSize(80, 80))
        self.btnMinus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMinus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnMinus.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnMinus.setObjectName("btnMinus")
        self.gridLayout.addWidget(self.btnMinus, 3, 3, 1, 1)
        self.btnFive = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFive.setMinimumSize(QtCore.QSize(80, 80))
        self.btnFive.setMaximumSize(QtCore.QSize(80, 80))
        self.btnFive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFive.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnFive.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnFive.setObjectName("btnFive")
        self.gridLayout.addWidget(self.btnFive, 2, 1, 1, 1)
        self.btnSix = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSix.setMinimumSize(QtCore.QSize(80, 80))
        self.btnSix.setMaximumSize(QtCore.QSize(80, 80))
        self.btnSix.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSix.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSix.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;\n"
"")
        self.btnSix.setObjectName("btnSix")
        self.gridLayout.addWidget(self.btnSix, 2, 2, 1, 1)
        self.btnPlus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnPlus.setMinimumSize(QtCore.QSize(80, 80))
        self.btnPlus.setMaximumSize(QtCore.QSize(80, 80))
        self.btnPlus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPlus.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnPlus.setObjectName("btnPlus")
        self.gridLayout.addWidget(self.btnPlus, 2, 3, 1, 1)
        self.btnEight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnEight.setMinimumSize(QtCore.QSize(80, 80))
        self.btnEight.setMaximumSize(QtCore.QSize(80, 80))
        self.btnEight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnEight.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnEight.setObjectName("btnEight")
        self.gridLayout.addWidget(self.btnEight, 1, 1, 1, 1)
        self.btnNine = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnNine.setMinimumSize(QtCore.QSize(80, 80))
        self.btnNine.setMaximumSize(QtCore.QSize(80, 80))
        self.btnNine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNine.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNine.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnNine.setObjectName("btnNine")
        self.gridLayout.addWidget(self.btnNine, 1, 2, 1, 1)
        self.btnTimes = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnTimes.setMinimumSize(QtCore.QSize(80, 80))
        self.btnTimes.setMaximumSize(QtCore.QSize(80, 80))
        self.btnTimes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTimes.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnTimes.setStyleSheet("background-color: #142273;\n"
"color: #f2f2f2;\n"
"border-radius: 40px;\n"
"font-family: sans-serif, \"Roboto\";\n"
"font-weight: bold;\n"
"font-size:40px;")
        self.btnTimes.setObjectName("btnTimes")
        self.gridLayout.addWidget(self.btnTimes, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.btnsContainer)
        MainWindow.setCentralWidget(self.centralwidget)

# WORKSPACE
        
        # DEFINING FUNTIONS FOR EVENTS
        
        def fixExpression(text):
                #Function example from: https://www.youtube.com/watch?v=J_ThzcfytGk&list=LL9dEU8mi26lMIkcZuWb89aw
                
                # Change everything that is different from 0123456789./*-+ to nothing
                text = re.sub(r'[^\d\.\/\*\-\+\(\)e]', r'', text, 0)
                
                # Change repeated signals
                text = re.sub(r'([\.\+\/\-])\1+', r'\1', text, 0)
                #text = re.sub(r'([\*])\2+', r'\2', text, 0)
                
                # Changes () or *() to nothing
                text = re.sub(r'\*?\(\)', '', text)
                
                return text
        
        def showNumberOnResult(btnValue):
                # Receive de value of button, and set text to display label
                txt = self.lblResult.text()
                if txt == "0" or txt =="":
                        txt = btnValue
                else:
                        txt = txt + btnValue
                
                self.lblResult.setText(fixExpression(text = txt))
                
        def getEquation(text):
                return re.split(r'\^', text, 0)
                
        def calculate():
                fixed = fixExpression(text = self.lblResult.text())
                equations = getEquation(fixed)
                print(equations)
                try:
                        if len(equations) == 1:
                                result = eval(fixExpression(equations[0]))
                        else:
                                result = eval(fixExpression(equations[0]))
                                
                                for equation in equations[1:]:
                                        result = math.pow(result, eval(fixExpression(equation)))
                        
                        self.lblResult.setText("0")
                        self.lblExpression.setText(f'{fixed}={result}')
                                        
                except OverflowError:
                        self.lblExpression.setText("Não consigo realizar essa conta :(")
                        clear()
                except Exception as e:
                        print(e)
                        self.lblExpression.setText("Conta inválida")
                        clear()
        
        def clear():
                self.lblResult.setText("0")
                
        
        # Creating events
                      
        self.btnZero.clicked.connect(lambda: showNumberOnResult("0"))
        self.btnOne.clicked.connect(lambda: showNumberOnResult("1"))
        self.btnTwo.clicked.connect(lambda: showNumberOnResult("2"))
        self.btnThree.clicked.connect(lambda: showNumberOnResult("3"))
        self.btnFour.clicked.connect(lambda: showNumberOnResult("4"))
        self.btnFive.clicked.connect(lambda: showNumberOnResult("5"))
        self.btnSix.clicked.connect(lambda: showNumberOnResult("6"))
        self.btnSeven.clicked.connect(lambda: showNumberOnResult("7"))
        self.btnEight.clicked.connect(lambda: showNumberOnResult("8"))
        self.btnNine.clicked.connect(lambda: showNumberOnResult("9"))
        self.btnMinus.clicked.connect(lambda: showNumberOnResult("-"))
        self.btnPlus.clicked.connect(lambda: showNumberOnResult("+"))
        self.btnTimes.clicked.connect(lambda: showNumberOnResult("*"))
        self.btnDivision.clicked.connect(lambda: showNumberOnResult("/"))
        self.btnDot.clicked.connect(lambda: showNumberOnResult("."))
        self.btnP1.clicked.connect(lambda: showNumberOnResult("("))
        self.btnP2.clicked.connect(lambda: showNumberOnResult(")"))
        self.btnElevate.clicked.connect(lambda: showNumberOnResult("**"))
        
        self.btnClear.clicked.connect(lambda: clear())
        
        self.btnEquals.clicked.connect(lambda: calculate())
        
# WORKSPACE END

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalcPy "))
        self.lblExpression.setText(_translate("MainWindow", "0"))
        self.lblResult.setText(_translate("MainWindow", "0"))
        self.btnClear.setText(_translate("MainWindow", "C"))
        self.btnDivision.setText(_translate("MainWindow", "/"))
        self.btnP1.setText(_translate("MainWindow", "("))
        self.btnP2.setText(_translate("MainWindow", ")"))
        self.btnSeven.setText(_translate("MainWindow", "7"))
        self.btnFour.setText(_translate("MainWindow", "4"))
        self.btnOne.setText(_translate("MainWindow", "1"))
        self.btnElevate.setText(_translate("MainWindow", "**"))
        self.btnZero.setText(_translate("MainWindow", "0"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnEquals.setText(_translate("MainWindow", "="))
        self.btnTwo.setText(_translate("MainWindow", "2"))
        self.btnThree.setText(_translate("MainWindow", "3"))
        self.btnMinus.setText(_translate("MainWindow", "-"))
        self.btnFive.setText(_translate("MainWindow", "5"))
        self.btnSix.setText(_translate("MainWindow", "6"))
        self.btnPlus.setText(_translate("MainWindow", "+"))
        self.btnEight.setText(_translate("MainWindow", "8"))
        self.btnNine.setText(_translate("MainWindow", "9"))
        self.btnTimes.setText(_translate("MainWindow", "x"))
